import type { BrewMethodId, MethodGuide } from '../models';

export const METHOD_GUIDES: Record<BrewMethodId, MethodGuide> = {
  v60: {
    methodId: 'v60',
    summary: 'Cone pour over. Fast, expressive, and unforgiving of poor pouring.',
    technique: [
      'Rinse the paper and warm the cone; discard the rinse water.',
      'Bloom with 2–3× the dose, then wait 30–45 s for the bed to settle.',
      'Pour in 2–4 even pulses, keeping the bed flat and the water level stable.',
      'A gentle swirl near the end levels the bed and speeds the drawdown.',
    ],
    healthy: {
      doseG: { min: 12, max: 22 },
      ratio: { min: 15, max: 17 },
      waterTempC: { min: 88, max: 96 },
      totalTimeS: { min: 120, max: 210 },
      bloomWaterRatio: { min: 2, max: 3 },
      bloomWaitS: { min: 30, max: 45 },
      pourCount: { min: 2, max: 4 },
    },
    requiredStepKinds: ['bloom', 'pour'],
    canonicalRecipeName: 'V60 — classic 1:16.7',
  },
  chemex: {
    methodId: 'chemex',
    summary: 'Thick-filter pour over. Clean and sweet, with a slow drawdown.',
    technique: [
      'Rinse the thick paper thoroughly; it carries a lot of papery flavour.',
      'Grind noticeably coarser than for a V60.',
      'Bloom with a longer wait than a V60, then pour in few, large pulses.',
      'Keep the water level below the spout to avoid channeling.',
    ],
    healthy: {
      doseG: { min: 22, max: 40 },
      ratio: { min: 15, max: 17 },
      waterTempC: { min: 90, max: 96 },
      totalTimeS: { min: 210, max: 300 },
      bloomWaterRatio: { min: 2, max: 3 },
      bloomWaitS: { min: 30, max: 60 },
      pourCount: { min: 2, max: 3 },
    },
    requiredStepKinds: ['bloom', 'pour'],
    canonicalRecipeName: 'Chemex — 1:16.7',
  },
  kalita: {
    methodId: 'kalita',
    summary: 'Flat-bed pour over. Even, repeatable, and tolerant of technique.',
    technique: [
      'Rinse the wavy filter and seat it evenly in the flat bed.',
      'Bloom short, then pour multiple small, even pulses.',
      'The flat bed is the identity of this method: more, smaller pulses than a V60.',
      'Avoid pouring directly onto the paper; keep the bed level.',
    ],
    healthy: {
      doseG: { min: 15, max: 25 },
      ratio: { min: 15, max: 17 },
      waterTempC: { min: 88, max: 96 },
      totalTimeS: { min: 150, max: 240 },
      bloomWaterRatio: { min: 2, max: 3 },
      bloomWaitS: { min: 30, max: 45 },
      pourCount: { min: 3, max: 5 },
    },
    requiredStepKinds: ['bloom', 'pour'],
    canonicalRecipeName: 'Kalita Wave — 1:16',
  },
  'french-press': {
    methodId: 'french-press',
    summary: 'Full-immersion with a metal or cloth filter. Rich and full-bodied.',
    technique: [
      'Add all the water at once and start the timer.',
      'Steep 4:00 with the crust intact.',
      'Break the crust with a stir, then skim the floating grounds.',
      'Press slowly and evenly; do not plunge hard.',
    ],
    healthy: {
      doseG: { min: 20, max: 40 },
      ratio: { min: 14, max: 17 },
      waterTempC: { min: 88, max: 96 },
      totalTimeS: { min: 210, max: 300 },
      bloomWaterRatio: null,
      bloomWaitS: null,
      pourCount: null,
    },
    requiredStepKinds: ['steep', 'press'],
    canonicalRecipeName: 'French Press — 4:00 steep',
  },
  aeropress: {
    methodId: 'aeropress',
    summary: 'Pressure-assisted immersion. Flexible and forgiving.',
    technique: [
      'Choose standard or inverted; note which in the recipe.',
      'Add water and steep for 1:00–2:00.',
      'Stir, then press slowly for 20–30 s.',
      'Stop at the hiss; do not force the last drops.',
    ],
    healthy: {
      doseG: { min: 12, max: 20 },
      ratio: { min: 10, max: 16 },
      waterTempC: { min: 80, max: 96 },
      totalTimeS: { min: 60, max: 150 },
      bloomWaterRatio: null,
      bloomWaitS: null,
      pourCount: null,
    },
    requiredStepKinds: ['steep', 'press'],
    canonicalRecipeName: 'AeroPress — 1:14.7',
  },
  clever: {
    methodId: 'clever',
    summary: 'Immersion with a valve. Steeps like a press, drains like a cone.',
    technique: [
      'Rinse the paper and seat it in the dripper.',
      'Add all the water with the valve closed and steep 2:00–2:30.',
      'Open the valve to drain; the drain step is required.',
      'A gentle stir before draining can speed it up.',
    ],
    healthy: {
      doseG: { min: 15, max: 25 },
      ratio: { min: 15, max: 17 },
      waterTempC: { min: 88, max: 96 },
      totalTimeS: { min: 150, max: 240 },
      bloomWaterRatio: null,
      bloomWaitS: null,
      pourCount: null,
    },
    requiredStepKinds: ['steep', 'drain'],
    canonicalRecipeName: 'Clever Dripper — 2:30 steep',
  },
  'cold-brew': {
    methodId: 'cold-brew',
    summary: 'Long cold immersion. Brewed in hours, drunk for days.',
    technique: [
      'Combine coarse grounds and cold water in a jar or carafe.',
      'Steep 12–18 hours in the fridge.',
      'Filter through a paper or cloth filter before serving.',
      'Dilute to taste; concentrate is stored at 1:8–1:10.',
    ],
    healthy: {
      doseG: { min: 60, max: 150 },
      ratio: { min: 8, max: 12 },
      waterTempC: { min: 4, max: 25 },
      totalTimeS: { min: 28800, max: 86400 },
      bloomWaterRatio: null,
      bloomWaitS: null,
      pourCount: null,
    },
    requiredStepKinds: ['add_water', 'steep', 'drain'],
    canonicalRecipeName: 'Cold Brew — 16 h steep',
  },
  espresso: {
    methodId: 'espresso',
    summary: 'Pump espresso. Dose and yield are the input pair, not dose and water.',
    technique: [
      'Dose, distribute and tamp level.',
      'Target a 1:2 yield in 25–30 s as a starting point.',
      'Adjust grind before adjusting anything else.',
      'Stop the shot on weight, not on colour alone.',
    ],
    healthy: {
      doseG: { min: 14, max: 22 },
      ratio: { min: 1.5, max: 2.5 },
      waterTempC: { min: 88, max: 96 },
      totalTimeS: { min: 20, max: 35 },
      bloomWaterRatio: null,
      bloomWaitS: null,
      pourCount: null,
    },
    requiredStepKinds: ['dose', 'extract', 'stop'],
    canonicalRecipeName: 'Espresso — 18 g in, 36 g out',
  },
  moka: {
    methodId: 'moka',
    summary: 'Stovetop pressure. No temperature control, so grind and heat matter.',
    technique: [
      'Fill the base with hot water up to the valve.',
      'Fill the basket level and level it without tamping.',
      'Assemble, then heat gently with the lid open.',
      'Remove from heat as soon as it gurgles and cool the base.',
    ],
    healthy: {
      doseG: { min: 14, max: 22 },
      ratio: { min: 7, max: 10 },
      waterTempC: { min: null, max: null },
      totalTimeS: { min: 180, max: 300 },
      bloomWaterRatio: null,
      bloomWaitS: null,
      pourCount: null,
    },
    requiredStepKinds: ['fill_water', 'fill_grounds', 'assemble', 'heat', 'stop'],
    canonicalRecipeName: 'Moka Pot — medium-fine',
  },
};

export function getMethodGuide(methodId: BrewMethodId): MethodGuide {
  return METHOD_GUIDES[methodId];
}
